version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn execute-script

workflows:
  version: 2
  commit:
    jobs:
      - build
  hourly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only: master
    jobs:
      - build